version: '3.7'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - JWT_SECRET=secret
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT=27017
      - TYPEORM_DATABASE=test
    ports:
      - "8080:8080"
    links:
      - postgres
    networks:
      - internal
      
  postgres:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - internal

networks:
  internal:
    driver: bridge