version: '3.7'
services:
  app:
    build: .
    environment:
      - PORT=3000
      - JWT_SECRET=secret
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_DATABASE=magna_db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=password
      - ETHEREUM_NODE_LIST=https://ethereumnodes.com
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=magna_db
    ports:
      - '5432:5432'
