name: One-click Run with Docker Compose CI

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu provided by GitHub Actions

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 4: Build Docker images defined in the docker-compose.yml file
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      # Step 5: Start Docker Compose in the background
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up &
          COMPOSE_PID=$!
          sleep 10  # Wait for a few seconds to let the services start

        # Step 6: Check if the service is running
      - name: Check service status
        run: |
          if curl -s http://localhost:3000; then
              echo "Service is running"
          else
              echo "Service is not running"
              # Bring Docker Compose back to foreground
              fg %1
              exit 1
              fi

        # Step 7: Tear down Docker Compose
      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
        if: always()
        # The 'if: always()' condition ensures this step runs even if previous steps fail
